import Footer from '@/components/Footer';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} flex flex-col h-screen w-screen overflow-y-auto`}
      >
        <Header />
        <div className={`flex flex-col w-[900px] mx-auto mt-32`}>
          <main className='w-full'>{children}</main>
        </div>
      <Footer />
      </body>
    </html>
  );
}
